# Generated by Django 3.2.13 on 2022-06-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptienda', '0003_auto_20220613_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='', max_length=40, verbose_name='direccion'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='', max_length=9, verbose_name='telefono'),
        ),
    ]
