# Generated by Django 3.2.13 on 2022-06-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptienda', '0004_auto_20220626_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='', max_length=20, verbose_name='Nombre'),
        ),
    ]
