# Generated by Django 3.2.13 on 2022-06-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptienda', '0005_alter_producto_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='', max_length=50, verbose_name='descripcion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='valor',
            field=models.CharField(default='', max_length=25, verbose_name='Valor'),
        ),
    ]
